pyprobe/analysis/base/degradation_mode_analysis_functions.py
pyprobe/analysis/degradation_mode_analysis.py

Fix call to `scipy.optimize.minimize` to bound the fitted stoichometry limits between 0 and 1

Add bounds to the minimize optimizer used for ocv fitting

---

pyprobe/cyclers/basecycler.py

This pull request includes a small but important change to the `read_file` function in the `pyprobe/cyclers/basecycler.py` file. The change ensures that file extensions are handled in a case-insensitive manner.
* [`pyprobe/cyclers/basecycler.py`](diffhunk://#diff-fb018c144804be12e36facbe6465c3e28413496785903af39a0073e3ffbd3a57L161-R161): Modified the `read_file` function to use `file_ext.lower()` in the `match` statement to handle file extensions in a case-insensitive manner.

Fix bug where upper case .CSV file not read

---

pyprobe/cell.py
pyprobe/filters.py
pyprobe/rawdata.py
pyprobe/result.py

This pull request includes several changes to the `pyprobe` package, primarily focusing on enhancing type annotations and simplifying class structures. The most important changes involve updating the `info` field to support nested dictionaries and removing re-definitions of inherited attributes from multiple classes.
* [`pyprobe/cell.py`](diffhunk://#diff-441aec132d927ef70cd9824112874874d1fb11d9d8bc0604c3b492ed3ad9a7c8L25-R25): Updated the `info` field in the `Cell` class to support nested dictionaries. This change is reflected in the type annotations and the corresponding field validator. [[1]](diffhunk://#diff-441aec132d927ef70cd9824112874874d1fb11d9d8bc0604c3b492ed3ad9a7c8L25-R25) [[2]](diffhunk://#diff-441aec132d927ef70cd9824112874874d1fb11d9d8bc0604c3b492ed3ad9a7c8L35-R36) …

Allow dict as info field

---

README.md
pyprobe/analysis/base/degradation_mode_analysis_functions.py
tests/analysis/test_dma.py

This pull request introduces a new function, `calc_full_cell_OCV_composite`, designed to calculate the full cell OCV for a cell featuring a composite negative electrode.
Inputs:
Positive electrode OCP
OCP of the constituents of the negative electrode
Capacity contribution of each constituent
Process:
The function first merges the constituent OCPs based on the common voltage window and their capacity contributions to form the composite negative electrode OCP.
It then aligns the composite negative electrode OCP with the positive electrode OCP to compute the full cell OCV.
Testing:
An accompanying test, `test_calc_full_cell_ocv_composite`, has been implemented and passes successfully.
Status:
No pre-commit issues were detected.

Calculation of Full Cell Open Circuit Voltage (OCV) for cells with Composite Negative Electrode

---

pyprobe/cyclers/basecycler.py
pyprobe/cyclers/biologic.py
tests/cyclers/test_basecycler.py

This pull request includes several changes to the `pyprobe/cyclers/basecycler.py` file and its corresponding test file. The changes focus on improving the handling of dataframes with missing columns and updating the concatenation method for dataframes. Additionally, a new test case has been added to verify the handling of missing columns.
* [`pyprobe/cyclers/basecycler.py`](diffhunk://#diff-fb018c144804be12e36facbe6465c3e28413496785903af39a0073e3ffbd3a57L182-R188): Modified the `_get_dataframe_list` method to fill missing columns with null values instead of excluding dataframes with missing columns.
* [`pyprobe/cyclers/basecycler.py`](diffhunk://#diff-fb018c144804be12e36facbe6465c3e28413496785903af39a0073e3ffbd3a57L204-R201): Updated the `get_imported_dataframe` method to use the …

Fix multi file reading where columns are missing in some files

---

docs/source/examples/examples.rst
docs/source/examples/sharing-data.ipynb

This pull request includes updates to the documentation by adding a new example for sharing data using PyProBE.
Documentation updates:
* [`docs/source/examples/examples.rst`](diffhunk://#diff-1aee17ec4d603e538a0ab2e514f2cb3c13a80656ca6e59618b0c91c101d185dcR9): Added a new entry for `sharing-data` to the examples list.
* [`docs/source/examples/sharing-data.ipynb`](diffhunk://#diff-f7fe37d3ca5db488bd5f859724fb5d3047e37f433cb56a2ef755553262d86bc8R1-R141): Created a new Jupyter notebook that demonstrates how to share data with PyProBE, using the `archive()` method, and retrieving archived objects.

Create sharing-data example

---

docs/source/examples/comparing-pyprobe-performance.ipynb
pyprobe/cell.py
tests/test_cell.py

This pull request includes several changes to the `pyprobe` project, focusing on adding new functionality for compression options and refactoring the code to improve clarity and maintainability.
* Added support for different compression priorities (`performance`, `file size`, `uncompressed`) when converting files to PyProBE format. (`[[1]](diffhunk://#diff-441aec132d927ef70cd9824112874874d1fb11d9d8bc0604c3b492ed3ad9a7c8L64-R110)`, `[[2]](diffhunk://#diff-441aec132d927ef70cd9824112874874d1fb11d9d8bc0604c3b492ed3ad9a7c8R122-R207)`, `[[3]](diffhunk://#diff-441aec132d927ef70cd9824112874874d1fb11d9d8bc0604c3b492ed3ad9a7c8R217-R219)`, `[[4]](diffhunk://#diff-441aec132d927ef70cd9824112874874d1fb11d9d8bc0604c3b492ed3ad9a7c8R241-L162)`)
* Updated the `process_cycler_file` and …

Add options for different compression levels for parquet files

---

pyprobe/cyclers/biologic.py
pyprobe/cyclers/neware.py
tests/cyclers/test_biologic.py
tests/cyclers/test_neware.py
tests/sample_data/biologic/Sample_data_biologic_timestamped.txt

* [`pyprobe/cyclers/biologic.py`](diffhunk://#diff-32774aee24ca8e95553b774cc303cbdabaefcdf26d368345377a1c7b355fd625R45-R65): Enhanced `read_file` method to handle timestamped data and convert timestamps to cumulative seconds if a specific datetime format is detected. [[1]](diffhunk://#diff-32774aee24ca8e95553b774cc303cbdabaefcdf26d368345377a1c7b355fd625R45-R65) [[2]](diffhunk://#diff-32774aee24ca8e95553b774cc303cbdabaefcdf26d368345377a1c7b355fd625L53-R79)
* [`pyprobe/cyclers/neware.py`](diffhunk://#diff-f98a123de8d0f3073501d715c5eafce742e688b1518a0715178cfc696e4fa5a6R26-R67): Added `_convert_neware_time_format` method to handle different Neware time formats and convert them to seconds. This method is now used in the `read_file` method to simplify time conversion logic. …

Fix time column reading for Neware and Biologic cyclers

---

pyprobe/analysis/pulsing.py

This pull request fixes a bug in `pulsing.py` where previous type requirements were expecting `"Experiment Capacity [Ah]"` to be available as a column, which may not be the case with the looser type requirements of the new method.
Column name standardization:
* Updated the column name from `"Experiment Capacity [Ah]"` to `"Capacity [Ah]"` in multiple places within the `get_resistances` function. [[1]](diffhunk://#diff-093ee3a38fdadafed5fe53a40e7e01df61e4a14f530abb558de9200c83f67781L196-R196) [[2]](diffhunk://#diff-093ee3a38fdadafed5fe53a40e7e01df61e4a14f530abb558de9200c83f67781L207-R207) [[3]](diffhunk://#diff-093ee3a38fdadafed5fe53a40e7e01df61e4a14f530abb558de9200c83f67781L216-R216)

Fix search for experiment capacity on pulsing module methods

---

pyprobe/plot.py

This pull request includes changes to the `pyprobe/plot.py` file to enhance compatibility and provide warnings for potential issues on specific platforms. The most important changes include importing necessary modules and adding a warning for Windows users about a known issue with the `show_image` method.
Platform compatibility and warnings:
* [`pyprobe/plot.py`](diffhunk://#diff-1bf1c7e92a3dffb62f089137efb973b16d6e598902e680fdece240899bd3f7c1R2-R3): Imported the `platform` and `warnings` modules to handle platform-specific behavior and issue warnings.
* [`pyprobe/plot.py`](diffhunk://#diff-1bf1c7e92a3dffb62f089137efb973b16d6e598902e680fdece240899bd3f7c1R65-R69): Added a warning in the `show_image` method to notify Windows users about the potential for the method to hang indefinitely, …

Add user warning when running show_image() on Windows

---

pyprobe/cyclers/neware.py
tests/cyclers/test_neware.py

This PR fixes the imported sheet in Neware `.xlsx` files to `'record'`. This should have no impact when only one sheet exists in the exported files, but means that PyProBE can extract the correct worksheet when multiple sheets have been exported.

Fix the sheet name to 'record' when importing Neware excel files

---

.github/workflows/ci.yml
.github/workflows/publish-to-pypi.yml
.github/workflows/publish-to-testpypi.yml
.github/workflows/sphinx.yml
.pre-commit-config.yaml
README.md
docs/source/developer_guide/developer_installation.rst
docs/source/user_guide/installation.rst
pyprobe/cell.py
pyprobe/rawdata.py
pyprobe/utils.py
pyproject.toml
tests/test_cell.py
tests/test_rawdata.py
uv.lock

This pull request includes several significant updates to the CI/CD workflows, documentation, and codebase of the PyProBE project. PyBaMM is removed as a dependency and uv is used for dependency management, packaging and publishing the project with GitHub actions.
* [`.github/workflows/ci.yml`](diffhunk://#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fL13-R36): Upgraded `actions/setup-python` to v5 and modified the installation steps to use `uv` for better dependency management. Added steps to install and run tests using `uv`. [[1]](diffhunk://#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fL13-R36) [[2]](diffhunk://#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fL40-R53)
* …

Remove pybamm required dependency and incorporate uv as a package manager

---

.github/workflows/ci.yml
.github/workflows/create-release-candidate.yml
.github/workflows/publish-to-pypi.yml
.github/workflows/sphinx.yml
docs/source/developer_guide/developer_installation.rst
docs/source/user_guide/installation.rst
pyprobe/plot.py
pyprobe/result.py
pyproject.toml
tests/test_cell.py
tests/test_plot.py
uv.lock

This pull request includes several changes to streamline dependency management and improve documentation for optional dependencies. The most important changes include modifying installation commands in various workflows and documentation, updating the handling of optional dependencies, and improving test coverage for optional dependencies.
* Simplified the `uv sync` command in multiple GitHub workflows by removing specific groups (`.github/workflows/ci.yml`, `.github/workflows/create-release-candidate.yml`, `.github/workflows/publish-to-pypi.yml`, `.github/workflows/sphinx.yml`). [[1]](diffhunk://#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fL32-R32) [[2]](diffhunk://#diff-a7d1ecec46c0cc4f70df2abd18a437b1ffa9eb50b8e06547ea60cf4402db609aL34-R34) …

Review dev and optional dependencies

---

README.md
docs/source/user_guide/plotting.rst

This pull request includes updates to the documentation to reflect changes in the plotting capabilities of PyProBE. The most important changes include updating the README and user guide to describe the new integrations with popular Python visualization tools.
Documentation updates:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L54-R54): Updated the description of the plotting capabilities to mention integration with `matplotlib`, `hvplot`, and `seaborn` instead of a built-in plotting module.
* [`docs/source/user_guide/plotting.rst`](diffhunk://#diff-4a1e09b951e042b62a4f8d20f32adf759fbe941932047b96053b7942d76cc510L6-L28): Revised the user guide to explain how to use the new plotting methods with `matplotlib`, `hvplot`, and `seaborn`, …

docs: update readme and user manual to reflect plotting integrations

---

.github/workflows/create-release-candidate.yml

This pull request includes an update to the GitHub Actions workflow for creating release candidates. The most important change is the upgrade of the action used to open pull requests.
* [`.github/workflows/create-release-candidate.yml`](diffhunk://#diff-a7d1ecec46c0cc4f70df2abd18a437b1ffa9eb50b8e06547ea60cf4402db609aL47-R47): Updated the `peter-evans/create-pull-request` action from version 4 to version 7.

chore: update workflow to v7 of create-pull-request gh action [skip ci]

---

.github/workflows/ci.yml
.github/workflows/coverage.yml
docs/source/examples/LEAN-differentiation.ipynb
docs/source/examples/analysing-GITT-data.ipynb
docs/source/examples/comparing-pyprobe-performance.ipynb
docs/source/examples/differentiating-voltage-data.ipynb
docs/source/examples/filtering-data.ipynb
docs/source/examples/getting-started.ipynb
docs/source/examples/ocv-fitting.ipynb
docs/source/examples/plotting.ipynb
docs/source/examples/working-with-pybamm-models.ipynb

This pull request includes changes to the testing configuration and several Jupyter notebooks in the documentation. The most important changes involve updating the testing command in the CI workflow and adding a new Jupyter magic command to suppress output in the notebooks.
Updates to CI workflow:
* [`.github/workflows/ci.yml`](diffhunk://#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fL53-R53): Modified the test command to ignore a specific notebook during testing. (`--ignore --nbmake docs/source/examples/comparing-pyprobe-performance.ipynb`)
Improvements to Jupyter notebooks:
* [`docs/source/examples/LEAN-differentiation.ipynb`](diffhunk://#diff-3c370a8e71bfa5b4f9230a585200edede1e728f18c854862b44cd8e7743d19a3R25-R38): Added `%%capture` to suppress output and …

Fix example output

---

docs/source/examples/working-with-pybamm-models.ipynb

This pull request includes a small change to the `docs/source/examples/working-with-pybamm-models.ipynb` file. The change adds a line to enable inline plotting with Matplotlib.
Changes in file `docs/source/examples/working-with-pybamm-models.ipynb`:
* Added `%matplotlib inline` to enable inline plotting with Matplotlib.

docs: add matplotlib inline to pybamm example

---

docs/source/examples/analysing-GITT-data.ipynb
docs/source/examples/comparing-pyprobe-performance.ipynb
docs/source/examples/differentiating-voltage-data.ipynb
docs/source/examples/filtering-data.ipynb
docs/source/examples/getting-started.ipynb
docs/source/examples/ocv-fitting.ipynb
docs/source/examples/plotting.ipynb
docs/source/examples/sharing-data.ipynb
docs/source/examples/working-with-pybamm-models.ipynb

This pull request includes changes to multiple Jupyter notebooks in the `docs/source/examples` directory. The main goal of these changes is to improve the structure and readability of the notebooks by separating the installation of dependencies into their own code cells.
Improvements to notebook structure:
* [`docs/source/examples/analysing-GITT-data.ipynb`](diffhunk://#diff-53553d4815ffbf58355dcb78b757c524044a92162ffd9e50183500c67825abadL22-R30): Moved the `%pip install matplotlib` command to its own code cell.
* [`docs/source/examples/comparing-pyprobe-performance.ipynb`](diffhunk://#diff-f97df501eeb86d9944940d597c2c80a87b666e5ecd0715eb1cd37238964dc9e1L20-R28): Moved the `%pip install matplotlib` and `%pip install pandas` commands to their own code cells.
* …

Fix parquet read speed example

---

pyprobe/result.py
tests/test_result.py

This pull request introduces a new feature to export data to a `.mat` file and includes the necessary tests for this functionality. The most important changes include importing required libraries, adding the `export_to_mat` method, and creating a test to verify the new method. Closes #216.
* [`pyprobe/result.py`](diffhunk://#diff-f6271fc55361775ee0d28df48b7f18a4ac1dfc4ba9e2e3005a512f807baca9b5R14-R15): Imported `savemat` from `scipy.io` and `re` module to support the new export functionality.
* [`pyprobe/result.py`](diffhunk://#diff-f6271fc55361775ee0d28df48b7f18a4ac1dfc4ba9e2e3005a512f807baca9b5R605-R631): Added `export_to_mat` method to the `Result` class to export data and info dictionary to a `.mat` file, ensuring MATLAB variable naming compliance by replacing non-alphanumeric …

feat: add capability to export any Result object to a .mat file

---

.github/workflows/ci-pull-request.yml
.github/workflows/ci-push.yml
.github/workflows/ci.yml
README.md
pyprobe/cell.py
tests/cyclers/test_basecycler.py
tests/test_cell.py
uv.lock

This pull request includes a change to the continuous integration (CI) workflow configuration in the `.github/workflows/ci.yml` file. The change updates the testing matrix to include multiple operating systems.
CI workflow configuration:
* [`.github/workflows/ci.yml`](diffhunk://#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fL25-R29): Modified the `runs-on` configuration to use a matrix of operating systems (`ubuntu-latest`, `windows-latest`, `macos-latest`) instead of only `ubuntu-latest`.

Bump dependencies and add windows and mac runners to ci workflows

---

.github/workflows/test-pypi-install.yml

This pull request makes a small update to the workflow file `.github/workflows/test-pypi-install.yml` to improve the reliability of the `test-pypi-install` job.
* The job now only runs if the triggering workflow completed successfully, ensuring tests are only executed after a successful workflow run.
* The workflow now checks out the repository using `actions/checkout@v4` before running the test steps, which is necessary for accessing the code during the job.

chore: fix pypi installation test workflow
